### ISSUE TITLE
Add `test` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/p-some#1]
Would be useful with a tester function, so you could get the first two promises that passes a check rather than just the first two promises.

Could be something like:

```js
pAny([p1, p2, p3, p4], {
  count: 2,
  test: value => value > 5
}).then(first => {
	console.log(first);
});
```

The above would return the first two promises that resolves to a value higher than 5.

Not sure about the naming. Alternatives:

- `validate`
- `check`

---

We should also move the `count` argument into an option.

**Comment by sindresorhus** [comment]
@kevva @SamVerschueren Thoughts?

**Comment by SamVerschueren** [comment]
Or `filter`?

**Comment by kevva** [comment]
> Or `filter`?

I like both this and `test` 👍

**Comment by sindresorhus** [comment]
Alright, let's go with `filter`.
